"""
This script is created to convert HTML file into the C header file with compressed HTML (as well as CSS and JavaScripts). 

Usage

    python html2header.py -f ./src/html/config.html -o /src/generated/ -v

Dependencies from pip:
 - minify_html
"""

import argparse
import logging
import sys
import os

try:
    import minify_html  # 3rd party package
except ImportError:
    minify_html = None


C_HEADER_TEMPLATE = """// ---------------------------------------------------------- //
// This file is autogenerated by html2header.py; do not edit! //
// ---------------------------------------------------------- //

#ifndef {capitalized_filename}_H_
#define {capitalized_filename}_H_

const char html_{lowercase_filename}[] = "{html_string}";

#endif  //  {capitalized_filename}_H_
"""
 

def main(input_filepth, output_filepath, skip_minify):
    logging.debug(f"Input path: {input_filepth}, output path: {output_filepath}")

    with open(input_filepth) as fp:
        input_file = fp.read()

    if not skip_minify:
        # Minify the HTML with the javascript
        minified_html = minify_html.minify(input_file, 
                                        do_not_minify_doctype=True, 
                                        minify_js=True,
                                        minify_css=True, 
                                        keep_html_and_head_opening_tags=False, 
                                        keep_closing_tags=False)
        logging.debug(minified_html)
    else:
        minified_html = input_file

    # Append HTML header
    minified_html = "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n" + minified_html

    # Escape characters
    escaped_html = minified_html.replace("\\", "\\\\")
    escaped_html = escaped_html.replace('"', '\\"')
    escaped_html = escaped_html.replace("'", "\\'")
    escaped_html = escaped_html.replace("\n", "\\n")
    escaped_html = escaped_html.replace("\r", "\\r")

    filename = os.path.basename(input_filepth)

    # Escape some basic illegal variable names
    filename = filename.replace('.', '_').replace('-', '_')
    
    c_header_string = C_HEADER_TEMPLATE.format(
        capitalized_filename=filename.upper(),
        lowercase_filename=filename.lower(),
        html_string=escaped_html,
    )
    logging.debug(c_header_string)

    # Write to the file
    with open(output_filepath, "w") as fp:
        fp.write(c_header_string)

    input_len = len(input_file)
    output_data_len = len(escaped_html)
    logging.info(f"Input HTML includes {input_len} bytes, the output escaped HTML includes {output_data_len} bytes")

    return 0



if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument('-f', '--input_filepath', help="Filepath to the HTML file that need to be converted to C header", required=True)
    parser.add_argument('-o', '--output_filepath', help="The output filepath that the C header will be written to", required=True)
    parser.add_argument('--no-minify', help="Do not minify the input file", default=False, action='store_true')

    parser.add_argument('-v', '--verbose', action='count', default=0)
    

    args = parser.parse_args()

    logging_levels = {0: logging.ERROR,
                      1: logging.DEBUG,
                      2: logging.INFO,
                      3: logging.WARNING,
                      4: logging.ERROR,
                      5: logging.CRITICAL}
    
    logging.basicConfig(stream=sys.stdout, level=logging_levels[args.verbose])

    main(args.input_filepath, args.output_filepath, skip_minify=args.no_minify)
